"""Generate manual step-by-step guides from the commands the tests actually run.

    pytest --record-commands ...        records results/<run-id>/commands.json
    python -m tools.gen_manual --from results/latest/commands.json
                                        collapses it into docs/manual/commands.json and renders
                                        docs/manual/PS-*.md for the GENERATED specs
    python -m tools.gen_manual          re-renders from the committed manifest
    python -m tools.gen_manual --check  fails if a generated guide is stale (no Docker needed)

Only the specs in GENERATED are rendered here. The other specs have hand-written guides in
docs/manual/, which spec-lint keeps tied to the spec's acceptance criteria.
"""

from __future__ import annotations

import argparse
import json
import shlex
import sys
from pathlib import Path

from tools import matrix as matrixmod
from tools import specs as specmod

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ("PS-001", "PS-002", "PS-005", "PS-013")
STEP_FIELDS = ("env", "entrypoint", "volumes", "cmd")


def collapse(events: list[dict], only: tuple[str, ...] = GENERATED) -> dict:
    """Reduce a raw event log to {spec: {"steps": [...]}}.

    A step is one distinct runtime command. A test that issued no command (it read a result
    cached by an earlier test of the same spec and tier) is credited to the step that ran last.
    """
    out: dict[str, dict] = {}
    last_step: dict[tuple[str, str | None], dict] = {}
    current: dict | None = None  # {"spec", "tier", "criteria", "issued"}

    def finish() -> None:
        if current and not current["issued"]:
            step = last_step.get((current["spec"], current["tier"]))
            if step:
                _add(step["covers"], current["criteria"])

    for event in events:
        if event["event"] == "test":
            finish()
            current = None
            if event["spec"] in only:
                current = {**event, "issued": False}
                out.setdefault(event["spec"], {"steps": []})
            continue
        if event["spec"] not in only or current is None:
            continue
        current["issued"] = True
        steps = out[event["spec"]]["steps"]
        step = next((s for s in steps if all(s[f] == event[f] for f in STEP_FIELDS)), None)
        if step is None:
            step = {f: event[f] for f in STEP_FIELDS} | {"covers": [], "families": []}
            steps.append(step)
        _add(step["covers"], current["criteria"])
        _add(step["families"], [event["family"] or "any"])
        last_step[(current["spec"], current["tier"])] = step
    finish()

    for entry in out.values():
        for step in entry["steps"]:
            step["covers"].sort(key=lambda ac: int(ac[2:]))
            step["families"].sort()
    return out


def _add(target: list, items: list) -> None:
    target += [i for i in items if i not in target]


def shell_command(step: dict) -> str:
    """Render one recorded runtime command as a `docker run` line."""
    parts = ["docker", "run", "--rm"]
    for key, value in step["env"].items():
        parts += ["-e", f"{key}={value}"]
    for volume in step["volumes"]:
        parts += ["-v", volume]
    if step["entrypoint"] is not None:
        parts += ["--entrypoint", step["entrypoint"]]
    return " ".join([*(shlex.quote(p) for p in parts), '"$IMAGE"', *map(shlex.quote, step["cmd"])])


def _example_images(matrix: matrixmod.Matrix, tiers: list[str]) -> list[tuple[str, str, str, str]]:
    """(tier, osrf ref, oeros ref, sloretz ref) for each tier, from images.yaml (tags, not digests).

    The oeros ref is the amd64 one; arm64 uses the same repository with a lyrical-arm64 tag
    (see tools/matrix.py:oeros_name). A tier without a sloretz image shows a dash.
    """
    rows = []
    for tier in tiers:
        entry = matrix.entry(tier)
        osrf = f"{entry['osrf']['repo']}:{entry['osrf']['tag']}"
        name = matrixmod.oeros_name(entry["oeros"], matrix.defaults["oeros_tag"], "amd64")
        oeros = f"{matrix.defaults['oeros_registry']}/{name}"
        sloretz = entry.get("sloretz")
        sloretz_ref = f"{sloretz['repo']}:{sloretz['tag']}" if sloretz else "—"
        rows.append((tier, osrf, oeros, sloretz_ref))
    return rows


def render(spec: specmod.Spec, entry: dict, matrix: matrixmod.Matrix) -> str:
    lines = [
        f"# {spec.id}: {spec.title}",
        "",
        "> Generated by `python -m tools.gen_manual` from the commands the automated tests run.",
        "> Do not edit: change the test and regenerate.",
        "",
        f"Spec: [`{spec.path.name}`](../../specs/{spec.path.name}). Source: `{spec.source}`.",
        "",
        "## Before you start",
        "",
        "Run every step once with the OSRF image and once with the oeros image, and compare the "
        "results. Set `IMAGE` to the image under test. The pairs for this spec's tiers are below "
        "(the suite pins the OSRF and sloretz ones by digest):",
        "",
        "| Tier | OSRF image | oeros image | sloretz image |",
        "| --- | --- | --- | --- |",
        *[
            f"| `{t}` | `{o}` | `{e}` | {s if s == '—' else f'`{s}`'} |"
            for t, o, e, s in _example_images(matrix, spec.applicable_tiers(matrix))
        ],
        "",
        "```sh",
        "IMAGE=<one of the images above>",
        "```",
        "",
        "The commands use `docker`; with rootless podman replace `docker` with `podman`.",
        "",
    ]
    for number, step in enumerate(entry["steps"], 1):
        lines += [f"## Step {number}", "", "```sh", shell_command(step), "```", ""]
        if step["families"] not in (["any"], ["oeros", "osrf"]):
            lines += [f"Run with the {' and '.join(step['families'])} image only.", ""]
        if step["covers"]:
            lines += ["Expected:", ""]
            lines += [f"- **{ac}**: {spec.criteria[ac]}" for ac in step["covers"]]
            lines += [""]
    return "\n".join(lines)


def guide_path(spec: specmod.Spec, root: Path = ROOT) -> Path:
    return root / "docs" / "manual" / spec.path.name


def render_all(root: Path, manifest: dict) -> dict[Path, str]:
    specs = specmod.load_all(root / "specs")
    matrix = matrixmod.load(root / "images.yaml")
    return {
        guide_path(specs[spec_id], root): render(specs[spec_id], entry, matrix)
        for spec_id, entry in sorted(manifest.items())
    }


def stale_guides(root: Path = ROOT) -> list[str]:
    """Problems with the generated guides, judged from the committed manifest only."""
    manifest_path = root / "docs" / "manual" / "commands.json"
    if not manifest_path.exists():
        return ["docs/manual/commands.json is missing; run python -m tools.gen_manual --from ..."]
    manifest = json.loads(manifest_path.read_text())
    problems = [
        f"{spec_id} has no recorded commands" for spec_id in GENERATED if spec_id not in manifest
    ]
    for path, text in render_all(root, manifest).items():
        if not path.exists() or path.read_text() != text:
            problems.append(f"{path.relative_to(root)} is stale; run python -m tools.gen_manual")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--from", dest="source", help="commands.json from a recorded run")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        problems = stale_guides()
        for problem in problems:
            print(f"gen_manual: {problem}", file=sys.stderr)
        return 1 if problems else 0

    manifest_path = ROOT / "docs" / "manual" / "commands.json"
    if args.source:
        manifest = collapse(json.loads(Path(args.source).read_text()))
        missing = [s for s in GENERATED if s not in manifest]
        if missing:
            print(f"gen_manual: no recorded commands for {', '.join(missing)}", file=sys.stderr)
            return 1
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest, indent=1, sort_keys=True) + "\n")
    else:
        manifest = json.loads(manifest_path.read_text())
    for path, text in render_all(ROOT, manifest).items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
